<?php

/**
 * @file
 * Allows user account and profile attributes to be automatically populated
 * using tokens. Provides basic tokens for attributes returned by the CAS
 * server.
 */

/**
 * Implements hook_menu().
 */
function cas_attributes_menu() {
  $items = array();

  $items['admin/config/people/cas/attributes'] = array(
    'title' => 'Attributes',
    'description' => 'Manage the relationships between CAS attributes and user fields.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cas_attributes_admin_settings'),
    'access arguments' => array('administer cas'),
    'file' => 'cas_attributes.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => -8,
  );
  $items['admin/config/people/cas/attributes/cas'] = array(
    'title' => 'CAS Attribute Tokens',
    'description' => 'Get a list of all available CAS Attributes',
    'page callback' => 'cas_attributes_list',
    'access arguments' => array('administer cas'),
    'file' => 'cas_attributes.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => -8,
  );

  return $items;
}

/**
 * Implements hook_cas_user_presave().
 */
function cas_attributes_cas_user_presave(&$edit, $account) {
  $cas_attributes = variable_get('cas_attributes', array());
  $cas_attributes += array('sync_every_login' => NULL, 'relations' => array('mail' => NULL, 'name' => NULL));

  // We synchronize on the first login (always) and on future logins (if chosen).
  if ($account->login && !$cas_attributes['sync_every_login']) {
    // The user has logged in before and we are not set to always synchronize.
    return;
  }

  $data = array('cas' => $edit['cas_user']['name']);

  // Set each drupal field to its mapped attribute.
  foreach ($cas_attributes['relations'] as $drupal_field => $text) {
    $result = trim(token_replace($text, $data, array('clear' => TRUE)));

    // Only update the fields if there is data to set.
    if (!empty($result)) {
      if ($drupal_field == 'name' || $drupal_field == 'mail') {
        $edit[$drupal_field] = $result;
      }
      else {
        $edit[$drupal_field][LANGUAGE_NONE][0]['value'] = $result;
      }
    }
  }
}
